name: Patrik Berger osobný blog
markdown: kramdown
gallerytag:
    dir: images/
    url: /images
    thumb_width: 150
    thumb_height: 150
    columns: 4
collections:
 - chessgames

gems: [jekyll-youtube, rmagick]    